import Link from 'next/link';
import { ArrowRight, CheckCircle2, HeartHandshake, ShieldCheck, Sparkles } from 'lucide-react';
import { Counters } from '@/components/Counters';
import { FocusGrid } from '@/components/FocusGrid';
import { ProjectCard, NewsCard, EventCard } from '@/components/Cards';
import { Reveal } from '@/components/Reveal';
import { getEvents, getNews, getProjects } from '@/lib/data';

export default async function Home(){
 const [projects,news,events]=await Promise.all([getProjects(true),getNews(),getEvents()]);
 return <>
 <section className="hero"><div className="container hero-grid"><Reveal className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> Rooted in South Punjab. Open to humanity.</span><h1 className="display">Dignity today. <span className="gradient-text">Opportunity tomorrow.</span></h1><p>Waseb Amanat Foundation works with communities to strengthen healthcare, education, emergency response, clean water, skills and long-term resilience.</p><div className="hero-actions"><Link className="btn btn-accent" href="/donate">Donate now <HeartHandshake size={18}/></Link><Link className="btn btn-secondary" href="/volunteers">Become a volunteer</Link><Link className="btn btn-ghost" href="/projects">Explore projects <ArrowRight size={17}/></Link></div><div className="trust-strip"><span><ShieldCheck size={17}/> Transparent systems</span><span><CheckCircle2 size={17}/> Community-led action</span><span><CheckCircle2 size={17}/> Measurable outcomes</span></div></Reveal><Reveal className="hero-visual"><div className="hero-photo"><img src="https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?auto=format&fit=crop&w=1300&q=85" alt="Humanitarian support for children and communities"/></div><div className="floating-stat glass one"><strong>15</strong><span className="small muted">Focus areas</span></div><div className="floating-stat glass two"><strong>24/7</strong><span className="small muted">Emergency readiness</span></div><div className="floating-stat glass three"><strong>Waseb</strong><span className="small muted">Local trust. Shared responsibility.</span></div></Reveal></div></section>
 <section className="section"><div className="container"><Reveal><div className="section-head center"><span className="eyebrow">What we do</span><h2 className="display-2">Humanitarian action designed around real lives</h2><p className="lead">From urgent relief to long-term opportunity, our programs are built to be practical, respectful and locally accountable.</p></div></Reveal><FocusGrid limit={6}/><div className="center" style={{marginTop:30}}><Link className="btn btn-ghost" href="/focus-areas">See all focus areas</Link></div></div></section>
 <Counters/>
 <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Featured projects</span><h2 className="display-2">Where your support moves</h2><p>Projects below are database-driven once Supabase is connected. Seed content keeps the site presentable before launch data is entered.</p></div><div className="grid-3">{projects.slice(0,3).map(p=><ProjectCard key={p.id} project={p}/>)}</div><div className="center" style={{marginTop:30}}><Link className="btn btn-primary" href="/projects">View all projects</Link></div></div></section>
 <section className="section section-soft"><div className="container grid-2" style={{alignItems:'center'}}><Reveal><div className="image-panel"><img src="https://images.unsplash.com/photo-1559027615-cd4628902d4a?auto=format&fit=crop&w=1200&q=80" alt="Volunteers working together"/></div></Reveal><Reveal><span className="eyebrow">Volunteer with purpose</span><h2 className="display-2">Your time can become someone’s turning point.</h2><p className="lead">Medical professionals, teachers, students, logisticians, photographers, community mobilizers and skilled volunteers all have a role.</p><Link className="btn btn-secondary" href="/volunteers">Join the volunteer network</Link></Reveal></div></section>
 <section className="section"><div className="container"><div className="section-head"><span className="eyebrow">Latest updates</span><h2 className="display-2">Stories, field updates and accountability</h2></div><div className="grid-3">{news.slice(0,3).map(n=><NewsCard key={n.id} post={n}/>)}</div></div></section>
 <section className="section section-soft"><div className="container"><div className="section-head"><span className="eyebrow">Upcoming</span><h2 className="display-2">Events and volunteer activities</h2></div><div className="grid-3">{events.slice(0,3).map(e=><EventCard key={e.id} event={e}/>)}</div></div></section>
 <section className="section"><div className="container"><div className="callout center"><span className="eyebrow">Amanat means responsibility</span><h2 className="display-2">Help us turn trust into measurable service.</h2><p className="lead" style={{marginInline:'auto'}}>Support a project, give monthly, volunteer your skills or connect us with a community that needs help.</p><div className="row" style={{justifyContent:'center'}}><Link className="btn btn-accent" href="/donate">Make a donation</Link><Link className="btn btn-ghost" href="/contact">Talk to our team</Link></div></div></div></section>
 </>
}
