'use client';
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarDays, FolderKanban, HeartHandshake, ImageIcon, Inbox, LayoutDashboard, LogOut, Mail, Newspaper, RefreshCw, Save, Trash2, Upload, Users } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';

type Tab='dashboard'|'projects'|'news_posts'|'events'|'gallery_items'|'volunteers'|'contact_messages'|'donations'|'newsletter_subscribers';
type Row=Record<string, any>;
const contentTabs:Tab[]=['projects','news_posts','events','gallery_items'];
const labels:Record<Tab,string>={dashboard:'Dashboard',projects:'Projects',news_posts:'News',events:'Events',gallery_items:'Gallery',volunteers:'Volunteers',contact_messages:'Messages',donations:'Donations',newsletter_subscribers:'Subscribers'};
const icons:Record<Tab,any>={dashboard:LayoutDashboard,projects:FolderKanban,news_posts:Newspaper,events:CalendarDays,gallery_items:ImageIcon,volunteers:Users,contact_messages:Inbox,donations:HeartHandshake,newsletter_subscribers:Mail};

export function AdminPanel({email}:{email:string}){
 const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const[tab,setTab]=useState<Tab>('dashboard');const[rows,setRows]=useState<Row[]>([]);const[counts,setCounts]=useState<Record<string,number>>({});const[loading,setLoading]=useState(false);const[editing,setEditing]=useState<Row|null>(null);const[notice,setNotice]=useState('');
 const loadCounts=useCallback(async()=>{const tables=['projects','news_posts','events','gallery_items','volunteers','contact_messages','donations','newsletter_subscribers'];const next:Record<string,number>={};await Promise.all(tables.map(async t=>{const{count}=await supabase.from(t).select('*',{count:'exact',head:true});next[t]=count||0}));setCounts(next)},[supabase]);
 const load=useCallback(async()=>{setLoading(true);setNotice('');if(tab==='dashboard'){await loadCounts();setRows([])}else{const order=tab==='events'?'event_date':tab==='news_posts'?'published_at':'created_at';const{data,error}=await supabase.from(tab).select('*').order(order,{ascending:false});if(error)setNotice(error.message);setRows(data||[])}setLoading(false)},[tab,supabase,loadCounts]);
 useEffect(()=>{load()},[load]);
 async function logout(){await supabase.auth.signOut();router.push('/admin/login');router.refresh()}
 async function remove(id:string){if(!confirm('Delete this record permanently?'))return;const{error}=await supabase.from(tab).delete().eq('id',id);if(error)setNotice(error.message);else load()}
 async function updateStatus(id:string,status:string){const{error}=await supabase.from(tab).update({status}).eq('id',id);if(error)setNotice(error.message);else load()}
 return <div className="admin-body"><div className="admin-layout"><aside className="admin-sidebar"><div className="brand"><img src="/logo.svg" alt="Logo"/><span>WAF Admin</span></div><nav>{(['dashboard','projects','news_posts','events','gallery_items','volunteers','contact_messages','donations','newsletter_subscribers'] as Tab[]).map(t=>{const I=icons[t];return <button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}><I size={17}/>{labels[t]}</button>})}</nav><div style={{marginTop:24,paddingTop:18,borderTop:'1px solid rgba(255,255,255,.12)'}}><p className="small" style={{color:'rgba(255,255,255,.6)',wordBreak:'break-all'}}>{email}</p><button onClick={logout}><LogOut size={17}/>Sign out</button><a href="/">← Public website</a></div></aside><main className="admin-main"><div className="admin-top"><div><span className="eyebrow">Operations console</span><h1>{labels[tab]}</h1></div><button className="btn btn-ghost btn-sm" onClick={load}><RefreshCw size={16}/>{loading?'Loading...':'Refresh'}</button></div>{notice&&<div className="form-status error" style={{marginBottom:16}}>{notice}</div>}{tab==='dashboard'?<Dashboard counts={counts}/>:contentTabs.includes(tab)?<ContentManager tab={tab} rows={rows} onEdit={setEditing} onDelete={remove}/>:<InboxTable tab={tab} rows={rows} onStatus={updateStatus} onDelete={remove}/>} {editing&&<EditModal tab={tab} row={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);load()}}/>}</main></div></div>
}

function Dashboard({counts}:{counts:Record<string,number>}){const cards=[['projects','Projects'],['volunteers','Volunteers'],['contact_messages','Messages'],['donations','Donations'],['news_posts','News posts'],['events','Events'],['gallery_items','Gallery items'],['newsletter_subscribers','Subscribers']];return <><div className="admin-kpis">{cards.map(([k,l])=><div className="card kpi" key={k}><span className="muted small">{l}</span><strong>{counts[k]||0}</strong></div>)}</div><div className="card feature-card" style={{marginTop:22}}><h3>Operational checklist</h3><p>Publish projects and updates, review volunteer applications and contact messages, reconcile donation records, and upload verified media. Public pages query published content automatically.</p></div></>}

function ContentManager({tab,rows,onEdit,onDelete}:{tab:Tab;rows:Row[];onEdit:(r:Row)=>void;onDelete:(id:string)=>void}){return <><div className="admin-toolbar"><p className="muted">{rows.length} records</p><button className="btn btn-primary btn-sm" onClick={()=>onEdit({})}>+ Add {labels[tab].replace(/s$/,'')}</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Title</th><th>Category</th><th>Status / Published</th><th>Date / Location</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.title||'(Untitled)'}</strong><br/><span className="small muted">{r.slug||r.media_type||''}</span></td><td>{r.category||'—'}</td><td>{String(r.published??r.status??'—')}</td><td>{r.location||r.event_date?.slice(0,10)||r.published_at?.slice(0,10)||'—'}</td><td><div className="row"><button className="btn btn-ghost btn-sm" onClick={()=>onEdit(r)}>Edit</button><button className="btn btn-danger btn-sm" onClick={()=>onDelete(r.id)}><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No records yet.</div>}</div></>}

function InboxTable({tab,rows,onStatus,onDelete}:{tab:Tab;rows:Row[];onStatus:(id:string,s:string)=>void;onDelete:(id:string)=>void}){return <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Person / Email</th><th>Details</th><th>Status</th><th>Received</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><strong>{r.name||r.donor_name||r.email}</strong><br/><span className="small muted">{r.email||r.phone||''}</span></td><td>{tab==='donations'?`PKR ${Number(r.amount||0).toLocaleString()} · ${r.cause||''}`:tab==='volunteers'?`${r.city||''} · ${(r.skills||[]).join(', ')}`:r.subject||r.message?.slice(0,90)||r.email}</td><td>{['volunteers','contact_messages','donations'].includes(tab)?<select className="status-select" value={r.status||'new'} onChange={e=>onStatus(r.id,e.target.value)}><option>new</option><option>reviewed</option><option>approved</option><option>contacted</option><option>completed</option><option>rejected</option></select>:<span className="badge">Active</span>}</td><td>{r.created_at?new Date(r.created_at).toLocaleDateString('en-PK'):'—'}</td><td><button className="btn btn-danger btn-sm" onClick={()=>onDelete(r.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No records yet.</div>}</div>}

function EditModal({tab,row,onClose,onSaved}:{tab:Tab;row:Row;onClose:()=>void;onSaved:()=>void}){const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[image,setImage]=useState(row.image_url||row.media_url||'');
 async function upload(file:File){setBusy(true);setError('');try{const ext=file.name.split('.').pop()||'jpg';const path=`${tab}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const{error}=await supabase.storage.from('media').upload(path,file,{upsert:false});if(error)throw error;const{data}=supabase.storage.from('media').getPublicUrl(path);setImage(data.publicUrl)}catch(e){setError(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const d=new FormData(e.currentTarget);try{let payload:Row={};if(tab==='projects')payload={title:d.get('title'),slug:slugify(String(d.get('slug')||d.get('title'))),excerpt:d.get('excerpt'),description:d.get('description'),category:d.get('category'),location:d.get('location'),image_url:image,goal_amount:Number(d.get('goal_amount')||0),raised_amount:Number(d.get('raised_amount')||0),beneficiaries:Number(d.get('beneficiaries')||0),status:d.get('status')||'Active',featured:d.get('featured')==='on',published:d.get('published')==='on'};if(tab==='news_posts')payload={title:d.get('title'),slug:slugify(String(d.get('slug')||d.get('title'))),excerpt:d.get('excerpt'),body:d.get('body'),category:d.get('category'),image_url:image,published_at:d.get('published_at')||new Date().toISOString(),published:d.get('published')==='on'};if(tab==='events')payload={title:d.get('title'),description:d.get('description'),category:d.get('category'),location:d.get('location'),event_date:d.get('event_date'),registration_url:d.get('registration_url')||null,image_url:image,published:d.get('published')==='on'};if(tab==='gallery_items')payload={title:d.get('title'),category:d.get('category'),media_type:d.get('media_type')||'image',media_url:image,thumbnail_url:image,published:d.get('published')==='on'};if(!image&&tab==='gallery_items')throw new Error('Upload or enter a media URL.');const q=row.id?supabase.from(tab).update(payload).eq('id',row.id):supabase.from(tab).insert(payload);const{error}=await q;if(error)throw error;onSaved()}catch(err){setError(err instanceof Error?err.message:'Save failed')}finally{setBusy(false)}}
 return <div className="admin-modal"><form className="card admin-modal-card" onSubmit={save}><div className="admin-top"><div><span className="eyebrow">{row.id?'Edit':'Create'}</span><h2>{labels[tab]}</h2></div><button type="button" className="btn btn-ghost btn-sm" onClick={onClose}>Close</button></div>{error&&<div className="form-status error">{error}</div>}<div className="form-grid"><Field name="title" label="Title" value={row.title} required/><Field name="category" label="Category" value={row.category} required/>{tab==='projects'&&<><Field name="slug" label="Slug" value={row.slug}/><Field name="location" label="Location" value={row.location}/><Field name="goal_amount" label="Funding goal (PKR)" type="number" value={row.goal_amount}/><Field name="raised_amount" label="Amount raised (PKR)" type="number" value={row.raised_amount}/><Field name="beneficiaries" label="Beneficiaries" type="number" value={row.beneficiaries}/><Field name="status" label="Status" value={row.status||'Active'}/><Text name="excerpt" label="Short description" value={row.excerpt}/><Text name="description" label="Full project description" value={row.description}/></>}{tab==='news_posts'&&<><Field name="slug" label="Slug" value={row.slug}/><Field name="published_at" label="Publish date" type="datetime-local" value={toLocal(row.published_at)}/><Text name="excerpt" label="Excerpt" value={row.excerpt}/><Text name="body" label="Article body" value={row.body}/></>}{tab==='events'&&<><Field name="location" label="Location" value={row.location}/><Field name="event_date" label="Event date/time" type="datetime-local" value={toLocal(row.event_date)} required/><Field name="registration_url" label="Registration URL" value={row.registration_url}/><Text name="description" label="Description" value={row.description}/></>}{tab==='gallery_items'&&<div className="field"><label>Media type</label><select name="media_type" defaultValue={row.media_type||'image'}><option value="image">Image</option><option value="video">Video URL</option></select></div>}<div className="field full"><label>Media image / URL</label><input value={image} onChange={e=>setImage(e.target.value)} placeholder="https://... or upload below"/><label className="btn btn-ghost btn-sm" style={{width:'max-content'}}><Upload size={15}/>Upload to Supabase<input type="file" accept="image/*" hidden onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label>{image&&<img src={image} alt="Preview" style={{maxHeight:180,borderRadius:16,objectFit:'cover'}}/>}</div>{tab==='projects'&&<label className="check-chip"><input type="checkbox" name="featured" defaultChecked={row.featured}/> Featured</label>}<label className="check-chip"><input type="checkbox" name="published" defaultChecked={row.published??true}/> Published</label><div className="field full"><button className="btn btn-primary" disabled={busy}><Save size={16}/>{busy?'Saving...':'Save'}</button></div></div></form></div>}
function Field({name,label,value='',type='text',required=false}:{name:string;label:string;value?:any;type?:string;required?:boolean}){return <div className="field"><label>{label}</label><input name={name} type={type} defaultValue={value??''} required={required}/></div>}
function Text({name,label,value=''}:{name:string;label:string;value?:any}){return <div className="field full"><label>{label}</label><textarea name={name} defaultValue={value??''}/></div>}
function slugify(v:string){return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function toLocal(v?:string){if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const off=d.getTimezoneOffset();return new Date(d.getTime()-off*60000).toISOString().slice(0,16)}
